---
abstract: 'Write Perl in Base64 encoding'
author:
  - 'Alan Haggai Alavi <alanhaggai@alanhaggai.org>'
build_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Base64
requires:
  Filter::Simple: 0
  MIME::Base64: 0
resources:
  repository: git://github.com/alanhaggai/Acme-Base64.git
version: 0.03
